# Generated by Django 3.0.6 on 2020-05-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='categoryimage',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_on',
            new_name='createdon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_on',
            new_name='createdon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='productdescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_discount_price',
            new_name='productdiscountprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='productimage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='productprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='productquantity',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='created_on',
            new_name='createdon',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory_image',
            new_name='subcategoryimage',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory_name',
            new_name='subcategoryname',
        ),
    ]
