# Generated by Django 3.0.6 on 2020-05-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200519_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobilen_umber',
            new_name='mobile_number',
        ),
    ]
