# Generated by Django 3.0.7 on 2020-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200519_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
