# Generated by Django 3.0.6 on 2020-05-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_image', models.ImageField(null=True, upload_to='uploads')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=30)),
                ('storelocation', models.CharField(max_length=30)),
                ('storeaddress', models.CharField(max_length=50)),
                ('storelatitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('storelongitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('storecity', models.CharField(max_length=25)),
                ('storestate', models.CharField(max_length=25)),
                ('createdon', models.DateTimeField(auto_now_add=True, null=True)),
                ('storeimage', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('subcategory_image', models.ImageField(null=True, upload_to='uploads')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Store')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_description', models.TextField(max_length=801)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Store')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Store'),
        ),
    ]
