# Generated by Django 3.0.6 on 2020-05-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_address_followership_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='building_name',
            new_name='buildingname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_name',
            new_name='streetname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_on',
            new_name='createdon',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
