# Generated by Django 3.0.6 on 2020-05-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200513_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followership',
        ),
    ]
